[package]
name = "micialware_ru"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"
getrandom = {version = "0.3.3", features = ["wasm_js"]}